### ISSUE TITLE
Error deploying github pages

### ISSUE THREAD

**Issue by aramacs** [dninomiya/cv#7]
Hey before pushing my changes  I follow the instructions to enable github page from my fork. However I'm having 404 error. 

![image](https://github.com/dninomiya/cv/assets/69637662/a1edb084-b86c-42b6-b454-6fa9534a74ba)

Also change the name of the link on description

![image](https://github.com/dninomiya/cv/assets/69637662/3d3364cc-512f-4e62-97f1-9a085c6e8921)

**Comment by dninomiya** [comment]
@aramacs 
Sorry for the late reply! Is the problem solved?

**Comment by aramacs** [comment]
Yeah, sometime later the page shows up. But not the CV it displays the Readme.
